import type { HubElementAction, HubElementStyle, HubElementType } from "@/types/hub-builder";
import { gameMenuPresetStyle } from "@/lib/game-menu-styles";

const ps = (id: string) => gameMenuPresetStyle(id) ?? {};

/** Categorías de la paleta del menú in-game (estilo Lunar Client). */
export type GameMenuPaletteCategory =
  | "game-nav"
  | "game-server"
  | "game-top-bar"
  | "game-widgets"
  | "game-dock"
  | "game-text"
  | "game-decor";

export const gameMenuCategoryLabels: Record<GameMenuPaletteCategory, string> = {
  "game-nav": "Navegación",
  "game-server": "Servidor / evento",
  "game-top-bar": "Barra superior",
  "game-widgets": "Widgets / paneles",
  "game-dock": "Barra inferior",
  "game-text": "Texto / info",
  "game-decor": "Decoración",
};

export const GAME_MENU_PALETTE_ORDER: GameMenuPaletteCategory[] = [
  "game-nav",
  "game-server",
  "game-top-bar",
  "game-widgets",
  "game-dock",
  "game-text",
  "game-decor",
];

export type GameMenuPaletteItem = {
  id: string;
  type: HubElementType;
  label: string;
  description: string;
  category: GameMenuPaletteCategory;
  defaultWidth: number;
  defaultHeight: number;
  defaultLabel: string;
  defaultAction: HubElementAction;
  defaultExternalUrl?: string;
  /** IP o dominio para action join-server. */
  defaultServerAddress?: string;
  defaultStyle?: Partial<HubElementStyle>;
  /** Solo visible en el editor; no se exporta al juego. */
  previewOnly?: boolean;
};

const DEFAULT_SERVER_HOST = "play.miservidor.net";

/** Elementos permitidos al editar el menú de Minecraft. */
export const gameMenuPalette: GameMenuPaletteItem[] = [
  // ── Navegación ──
  {
    id: "game.button",
    type: "button",
    label: "Botón",
    description: "Botón estándar (Singleplayer, Options…)",
    category: "game-nav",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Singleplayer",
    defaultAction: "play",
    defaultStyle: ps("vanilla"),
  },
  {
    id: "game.nav.play",
    type: "play-button",
    label: "Jugar",
    description: "Botón principal destacado",
    category: "game-nav",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Jugar",
    defaultAction: "play",
    defaultStyle: ps("store"),
  },
  {
    id: "game.nav.multi",
    type: "button",
    label: "Multiplayer",
    description: "Acceso a servidores multijugador",
    category: "game-nav",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Multiplayer",
    defaultAction: "none",
    defaultStyle: ps("lunar-wide"),
  },
  {
    id: "game.nav.store",
    type: "button",
    label: "Tienda",
    description: "Botón de tienda / enlace externo",
    category: "game-nav",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Store",
    defaultAction: "external",
    defaultExternalUrl: "https://store.example.com",
    defaultStyle: ps("store"),
  },
  {
    id: "game.nav.compact",
    type: "button",
    label: "Botón compacto",
    description: "Mitad de ancho (Options + Mods)",
    category: "game-nav",
    defaultWidth: 48,
    defaultHeight: 11,
    defaultLabel: "Options",
    defaultAction: "settings",
    defaultStyle: ps("compact"),
  },
  {
    id: "game.link",
    type: "link",
    label: "Enlace",
    description: "Abre Discord, YouTube u otra URL",
    category: "game-nav",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Discord",
    defaultAction: "external",
    defaultExternalUrl: "https://discord.com",
    defaultStyle: ps("discord"),
  },
  {
    id: "game.nav.quit",
    type: "button",
    label: "Salir",
    description: "Cierra el juego",
    category: "game-nav",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Quit Game",
    defaultAction: "none",
    defaultStyle: ps("danger"),
  },

  // ── Servidor / evento (conexión directa) ──
  {
    id: "game.server.join",
    type: "play-button",
    label: "Entrar al servidor",
    description: "Conecta directo sin pasar por la lista multijugador",
    category: "game-server",
    defaultWidth: 120,
    defaultHeight: 14,
    defaultLabel: "Entrar al servidor",
    defaultAction: "join-server",
    defaultServerAddress: DEFAULT_SERVER_HOST,
    defaultStyle: ps("store"),
  },
  {
    id: "game.server.hub",
    type: "button",
    label: "Lobby principal",
    description: "Hub / spawn del servidor",
    category: "game-server",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Lobby",
    defaultAction: "join-server",
    defaultServerAddress: `lobby.${DEFAULT_SERVER_HOST}`,
    defaultStyle: ps("lunar-wide"),
  },
  {
    id: "game.server.skyblock",
    type: "button",
    label: "Skyblock",
    description: "Modo islas — conexión directa",
    category: "game-server",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Skyblock",
    defaultAction: "join-server",
    defaultServerAddress: `skyblock.${DEFAULT_SERVER_HOST}`,
    defaultStyle: ps("skyblock"),
  },
  {
    id: "game.server.survival",
    type: "button",
    label: "Survival",
    description: "Mundo survival del servidor",
    category: "game-server",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Survival",
    defaultAction: "join-server",
    defaultServerAddress: `survival.${DEFAULT_SERVER_HOST}`,
    defaultStyle: ps("store"),
  },
  {
    id: "game.server.pvp",
    type: "button",
    label: "Arena PvP",
    description: "Combate jugador vs jugador",
    category: "game-server",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Arena PvP",
    defaultAction: "join-server",
    defaultServerAddress: `pvp.${DEFAULT_SERVER_HOST}`,
    defaultStyle: ps("pvp"),
  },
  {
    id: "game.server.minigames",
    type: "button",
    label: "Minijuegos",
    description: "BedWars, SkyWars, party games…",
    category: "game-server",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Minijuegos",
    defaultAction: "join-server",
    defaultServerAddress: `minigames.${DEFAULT_SERVER_HOST}`,
    defaultStyle: ps("minigame"),
  },
  {
    id: "game.server.event",
    type: "play-button",
    label: "Evento activo",
    description: "Botón destacado para evento temporal",
    category: "game-server",
    defaultWidth: 110,
    defaultHeight: 13,
    defaultLabel: "Evento en vivo",
    defaultAction: "join-server",
    defaultServerAddress: `evento.${DEFAULT_SERVER_HOST}`,
    defaultStyle: ps("event"),
  },
  {
    id: "game.server.creative",
    type: "button",
    label: "Creativo",
    description: "Mundo creativo / plots",
    category: "game-server",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Creativo",
    defaultAction: "join-server",
    defaultServerAddress: `creative.${DEFAULT_SERVER_HOST}`,
    defaultStyle: ps("outline"),
  },
  {
    id: "game.server.hardcore",
    type: "button",
    label: "Hardcore",
    description: "Modo hardcore / UHC",
    category: "game-server",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Hardcore",
    defaultAction: "join-server",
    defaultServerAddress: `hardcore.${DEFAULT_SERVER_HOST}`,
    defaultStyle: ps("danger"),
  },
  {
    id: "game.server.ranked",
    type: "button",
    label: "Competitivo",
    description: "Ranked / ladder / torneos",
    category: "game-server",
    defaultWidth: 98,
    defaultHeight: 11,
    defaultLabel: "Competitivo",
    defaultAction: "join-server",
    defaultServerAddress: `ranked.${DEFAULT_SERVER_HOST}`,
    defaultStyle: ps("ranked"),
  },
  {
    id: "game.server.practice",
    type: "button",
    label: "Práctica",
    description: "Entrenamiento / duelos rápidos",
    category: "game-server",
    defaultWidth: 72,
    defaultHeight: 11,
    defaultLabel: "Práctica",
    defaultAction: "join-server",
    defaultServerAddress: `practice.${DEFAULT_SERVER_HOST}`,
    defaultStyle: ps("compact"),
  },

  // ── Barra superior ──
  {
    id: "game.top.profile",
    type: "profile-widget",
    label: "Perfil",
    description: "Avatar + nombre de usuario",
    category: "game-top-bar",
    defaultWidth: 96,
    defaultHeight: 22,
    defaultLabel: "Usuario",
    defaultAction: "none",
    defaultStyle: ps("lunar-pill"),
    previewOnly: true,
  },
  {
    id: "game.top.avatar",
    type: "instance-avatar",
    label: "Avatar",
    description: "Cabeza / skin del jugador",
    category: "game-top-bar",
    defaultWidth: 32,
    defaultHeight: 32,
    defaultLabel: "Avatar",
    defaultAction: "none",
    previewOnly: true,
  },
  {
    id: "game.top.currency",
    type: "chip",
    label: "Monedas",
    description: "Contador de moneda / puntos",
    category: "game-top-bar",
    defaultWidth: 56,
    defaultHeight: 22,
    defaultLabel: "0",
    defaultAction: "none",
    defaultStyle: ps("gold"),
  },
  {
    id: "game.top.icon",
    type: "icon-button",
    label: "Icono",
    description: "Cerrar, ajustes o personalizar",
    category: "game-top-bar",
    defaultWidth: 28,
    defaultHeight: 28,
    defaultLabel: "Ajustes",
    defaultAction: "settings",
    defaultStyle: ps("ghost"),
  },

  // ── Widgets ──
  {
    id: "game.widget.quest",
    type: "surface-box",
    label: "Panel misión",
    description: "Caja de quest / recompensa",
    category: "game-widgets",
    defaultWidth: 180,
    defaultHeight: 90,
    defaultLabel: "Free Medal Quest",
    defaultAction: "none",
    defaultStyle: { backgroundColor: "#16181c", textColor: "#e8eaed", borderRadius: 12 },
    previewOnly: true,
  },
  {
    id: "game.widget.news",
    type: "news-card",
    label: "Noticias",
    description: "Carrusel de novedades / skins",
    category: "game-widgets",
    defaultWidth: 160,
    defaultHeight: 72,
    defaultLabel: "Noticias",
    defaultAction: "none",
    defaultStyle: { backgroundColor: "#12141a", textColor: "#e8eaed", borderRadius: 10 },
    previewOnly: true,
  },
  {
    id: "game.widget.banner",
    type: "banner",
    label: "Banner promo",
    description: "Promo Discord, eventos, etc.",
    category: "game-widgets",
    defaultWidth: 160,
    defaultHeight: 24,
    defaultLabel: "LINK YOUR DISCORD",
    defaultAction: "external",
    defaultExternalUrl: "https://discord.com",
    defaultStyle: { backgroundColor: "#5b2d8a", textColor: "#ffffff", borderRadius: 10 },
  },
  {
    id: "game.widget.stat",
    type: "stat-card",
    label: "Estadística",
    description: "K/D, tiempo jugado, rango…",
    category: "game-widgets",
    defaultWidth: 100,
    defaultHeight: 56,
    defaultLabel: "K/D 2.4",
    defaultAction: "none",
    defaultStyle: { backgroundColor: "#16181c", textColor: "#8b919a", borderRadius: 10 },
  },

  // ── Barra inferior ──
  {
    id: "game.dock.home",
    type: "icon-button",
    label: "Dock icono",
    description: "Botón cuadrado de la barra inferior",
    category: "game-dock",
    defaultWidth: 36,
    defaultHeight: 36,
    defaultLabel: "Inicio",
    defaultAction: "none",
    defaultStyle: { backgroundColor: "#1e2126", textColor: "#e8eaed", borderRadius: 10 },
  },
  {
    id: "game.dock.tab",
    type: "nav-item",
    label: "Pestaña dock",
    description: "Cosméticos, chat, idioma…",
    category: "game-dock",
    defaultWidth: 36,
    defaultHeight: 36,
    defaultLabel: "Cosméticos",
    defaultAction: "none",
    defaultStyle: { backgroundColor: "#16181c", textColor: "#c8cad0", borderRadius: 10 },
  },
  {
    id: "game.dock.row",
    type: "container",
    label: "Fila dock",
    description: "Contenedor horizontal de iconos",
    category: "game-dock",
    defaultWidth: 240,
    defaultHeight: 40,
    defaultLabel: "Dock",
    defaultAction: "none",
    previewOnly: true,
  },
  {
    id: "game.dock.divider",
    type: "divider",
    label: "Separador",
    description: "Línea divisoria horizontal",
    category: "game-dock",
    defaultWidth: 240,
    defaultHeight: 1,
    defaultLabel: "",
    defaultAction: "none",
    defaultStyle: { backgroundColor: "#2b2f36" },
    previewOnly: true,
  },

  // ── Texto / info ──
  {
    id: "game.text",
    type: "text",
    label: "Texto libre",
    description: "Texto estático personalizado",
    category: "game-text",
    defaultWidth: 220,
    defaultHeight: 10,
    defaultLabel: "Mi texto",
    defaultAction: "none",
    defaultStyle: { textColor: "#bfbfbf", fontSize: 8 },
  },
  {
    id: "game.text.logo",
    type: "text",
    label: "Logo MINECRAFT",
    description: "Título grande del menú vanilla",
    category: "game-text",
    defaultWidth: 200,
    defaultHeight: 28,
    defaultLabel: "MINECRAFT",
    defaultAction: "none",
    defaultStyle: { textColor: "#ffffff", fontSize: 22, fontWeight: "bold", gameMenuBinding: "minecraft_logo" },
  },
  {
    id: "game.text.java",
    type: "text",
    label: "Java Edition",
    description: "Subtítulo bajo el logo",
    category: "game-text",
    defaultWidth: 120,
    defaultHeight: 8,
    defaultLabel: "Java Edition",
    defaultAction: "none",
    defaultStyle: { textColor: "#888888", fontSize: 7, gameMenuBinding: "java_edition" },
  },
  {
    id: "game.text.forge",
    type: "text",
    label: "Versión Forge",
    description: "Línea inferior izquierda — Forge X.X.X",
    category: "game-text",
    defaultWidth: 160,
    defaultHeight: 8,
    defaultLabel: "Forge",
    defaultAction: "none",
    defaultStyle: { textColor: "#bfbfbf", fontSize: 8, gameMenuBinding: "forge_version" },
  },
  {
    id: "game.text.mc",
    type: "text",
    label: "Versión Minecraft",
    description: "Línea inferior izquierda — Minecraft X.X.X",
    category: "game-text",
    defaultWidth: 160,
    defaultHeight: 8,
    defaultLabel: "Minecraft",
    defaultAction: "none",
    defaultStyle: { textColor: "#bfbfbf", fontSize: 8, gameMenuBinding: "minecraft_version" },
  },
  {
    id: "game.text.mcp",
    type: "text",
    label: "MCP",
    description: "Identificador MCP de Forge",
    category: "game-text",
    defaultWidth: 200,
    defaultHeight: 8,
    defaultLabel: "MCP",
    defaultAction: "none",
    defaultStyle: { textColor: "#bfbfbf", fontSize: 8, gameMenuBinding: "mcp_version" },
  },
  {
    id: "game.text.mods",
    type: "text",
    label: "Mods cargados",
    description: "Contador de mods activos",
    category: "game-text",
    defaultWidth: 160,
    defaultHeight: 8,
    defaultLabel: "mods loaded",
    defaultAction: "none",
    defaultStyle: { textColor: "#bfbfbf", fontSize: 8, gameMenuBinding: "mods_loaded" },
  },
  {
    id: "game.text.forge-update",
    type: "text",
    label: "Aviso Forge",
    description: "Esquina inferior derecha — nueva versión",
    category: "game-text",
    defaultWidth: 220,
    defaultHeight: 8,
    defaultLabel: "Forge update",
    defaultAction: "none",
    defaultStyle: { textColor: "#8a8a8a", fontSize: 8, gameMenuBinding: "forge_update" },
  },
  {
    id: "game.text.disclaimer",
    type: "text",
    label: "Disclaimer",
    description: "Aviso legal (Mojang / Microsoft)",
    category: "game-text",
    defaultWidth: 260,
    defaultHeight: 10,
    defaultLabel: "Not affiliated with Mojang or Microsoft",
    defaultAction: "none",
    defaultStyle: { textColor: "#4b5563", fontSize: 7 },
  },
  {
    id: "game.text.status",
    type: "minecraft-status-chip",
    label: "Estado",
    description: "En línea, servidor, ping…",
    category: "game-text",
    defaultWidth: 120,
    defaultHeight: 18,
    defaultLabel: "En línea",
    defaultAction: "none",
    defaultStyle: { backgroundColor: "#1a2e1f", textColor: "#6b9e78", borderRadius: 999, fontSize: 7 },
  },
  {
    id: "game.text.hint",
    type: "launch-hint-text",
    label: "Consejo",
    description: "Tip o mensaje secundario",
    category: "game-text",
    defaultWidth: 200,
    defaultHeight: 12,
    defaultLabel: "Consejo: usa F11 para pantalla completa",
    defaultAction: "none",
    defaultStyle: { textColor: "#8b919a", fontSize: 8 },
  },

  // ── Decoración ──
  {
    id: "game.decor.logo",
    type: "image",
    label: "Logo",
    description: "Imagen / logo del cliente",
    category: "game-decor",
    defaultWidth: 64,
    defaultHeight: 64,
    defaultLabel: "Logo",
    defaultAction: "none",
    previewOnly: true,
  },
  {
    id: "game.decor.spacer",
    type: "spacer",
    label: "Espaciador",
    description: "Reserva espacio invisible",
    category: "game-decor",
    defaultWidth: 20,
    defaultHeight: 20,
    defaultLabel: "",
    defaultAction: "none",
    previewOnly: true,
  },
];
