import type { LucideIcon } from "lucide-react";
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Bell,
  BellRing,
  Blocks,
  Bookmark,
  Box,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleX,
  Clipboard,
  Clock,
  Code2,
  Columns2,
  Compass,
  Copy,
  CornerUpLeft,
  CreditCard,
  Crown,
  Download,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flame,
  Folder,
  FolderOpen,
  Fullscreen,
  Gamepad2,
  Globe,
  GripVertical,
  HardDrive,
  Hash,
  Heart,
  HelpCircle,
  Home,
  Image,
  Info,
  LayoutGrid,
  Link2,
  List,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessagesSquare,
  Mic,
  Minimize2,
  Minus,
  Monitor,
  MoreHorizontal,
  MoreVertical,
  Music,
  Package,
  Paintbrush,
  Palette,
  PanelLeft,
  PanelRight,
  PanelTop,
  Pause,
  Pickaxe,
  Pin,
  Play,
  Plus,
  Power,
  Puzzle,
  RefreshCw,
  RotateCw,
  Rows2,
  Rss,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  Shrink,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  Star,
  Sword,
  Tag,
  Terminal,
  Timer,
  Trash2,
  Trophy,
  Unlock,
  Upload,
  User,
  UserCircle,
  UserPlus,
  Users,
  Video,
  Volume2,
  VolumeX,
  X,
  Zap,
} from "lucide-react";
import {
  DEFAULT_HUB_ICON,
  resolveHubElementIconName,
  type HubElement,
} from "@craftlauncher/shared";

export const hubIconComponents: Record<string, LucideIcon> = {
  settings: Settings,
  play: Play,
  pause: Pause,
  square: Square,
  "refresh-cw": RefreshCw,
  "rotate-cw": RotateCw,
  download: Download,
  upload: Upload,
  save: Save,
  "trash-2": Trash2,
  plus: Plus,
  minus: Minus,
  check: Check,
  x: X,
  power: Power,
  "log-out": LogOut,
  "log-in": LogIn,
  copy: Copy,
  clipboard: Clipboard,
  "share-2": Share2,
  link: Link2,
  "external-link": ExternalLink,
  zap: Zap,
  sparkles: Sparkles,
  home: Home,
  menu: Menu,
  "layout-grid": LayoutGrid,
  list: List,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "corner-up-left": CornerUpLeft,
  compass: Compass,
  map: Map,
  folder: Folder,
  "folder-open": FolderOpen,
  "minimize-2": Minimize2,
  "maximize-2": Maximize2,
  "panel-left": PanelLeft,
  "panel-right": PanelRight,
  "panel-top": PanelTop,
  "columns-2": Columns2,
  "rows-2": Rows2,
  fullscreen: Fullscreen,
  shrink: Shrink,
  expand: Expand,
  bell: Bell,
  "bell-ring": BellRing,
  "message-circle": MessageCircle,
  "messages-square": MessagesSquare,
  mail: Mail,
  send: Send,
  users: Users,
  user: User,
  "user-circle": UserCircle,
  "user-plus": UserPlus,
  megaphone: Megaphone,
  rss: Rss,
  "gamepad-2": Gamepad2,
  puzzle: Puzzle,
  package: Package,
  box: Box,
  pickaxe: Pickaxe,
  sword: Sword,
  shield: Shield,
  crown: Crown,
  trophy: Trophy,
  flame: Flame,
  globe: Globe,
  server: Server,
  "hard-drive": HardDrive,
  blocks: Blocks,
  search: Search,
  filter: Filter,
  "sliders-horizontal": SlidersHorizontal,
  eye: Eye,
  "eye-off": EyeOff,
  lock: Lock,
  unlock: Unlock,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  info: Info,
  "help-circle": HelpCircle,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "circle-check": CircleCheck,
  "circle-x": CircleX,
  "loader-circle": LoaderCircle,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  "grip-vertical": GripVertical,
  pin: Pin,
  tag: Tag,
  hash: Hash,
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  image: Image,
  camera: Camera,
  video: Video,
  music: Music,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  mic: Mic,
  monitor: Monitor,
  smartphone: Smartphone,
  palette: Palette,
  paintbrush: Paintbrush,
  "code-2": Code2,
  terminal: Terminal,
  "file-text": FileText,
  "shopping-bag": ShoppingBag,
  "credit-card": CreditCard,
};

export function resolveHubIconComponent(iconId: string): LucideIcon {
  return hubIconComponents[iconId] ?? hubIconComponents[DEFAULT_HUB_ICON] ?? Settings;
}

type HubElementIconProps = {
  element: HubElement;
  size?: number;
  strokeWidth?: number;
  className?: string;
};

export function HubElementIcon({ element, size = 16, strokeWidth = 2, className }: HubElementIconProps) {
  const iconId = resolveHubElementIconName(element);
  const Icon = resolveHubIconComponent(iconId);
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden />;
}
