import type { HubElementType } from "@/types/hub-builder";
import {
  Activity,
  AlignLeft,
  Bell,
  Info,
  Box,
  CheckSquare,
  ChevronDown,
  Eye,
  EyeOff,
  Code2,
  FolderPlus,
  HardDrive,
  List,
  Users,
  UserCircle,
  FileInput,
  Container,
  Gamepad2,
  Globe,
  Hash,
  Image as ImageIcon,
  LayoutGrid,
  Link2,
  Megaphone,
  Minus,
  Monitor,
  MousePointer2,
  Newspaper,
  Package,
  PanelTop,
  Percent,
  Play,
  Puzzle,
  Rows,
  Search as SearchIcon,
  LayoutList,
  PanelRight,
  ScrollText,
  SeparatorVertical,
  SlidersHorizontal,
  Square,
  Timer,
  ToggleLeft,
  Type,
  User,
  Zap,
} from "lucide-react";

export const paletteIcons: Record<HubElementType, typeof Play> = {
  "play-button": Play,
  button: MousePointer2,
  "icon-button": Square,
  link: Link2,
  text: Type,
  "nav-item": LayoutGrid,
  image: ImageIcon,
  banner: Megaphone,
  "news-card": Newspaper,
  "modpack-slot": Package,
  "mods-catalog": Puzzle,
  "mods-tabs": Rows,
  "mods-search": SearchIcon,
  "mods-results": LayoutList,
  "mods-preview": PanelRight,
  "mods-install-log": ScrollText,
  "mods-installed-list": LayoutList,
  "mods-installed-search": SearchIcon,
  "instance-create-form": FolderPlus,
  "instance-list": List,
  "instance-active-card": UserCircle,
  "instance-avatar": UserCircle,
  "instance-avatar-grid": LayoutGrid,
  "instance-name-input": FileInput,
  "instance-version-select": Gamepad2,
  "instance-selector": Users,
  "installed-version-selector": HardDrive,
  "launch-panel": ScrollText,
  "launch-version-title": Type,
  "launch-phase-label": Activity,
  "launch-detail-text": AlignLeft,
  "launch-progress-bar": Percent,
  "launch-log-panel": ScrollText,
  "launch-structured-log": List,
  "launch-error-block": Info,
  "launch-ok-hint": Activity,
  "launch-hint-text": Info,
  "launch-dismiss-button": MousePointer2,
  "automation-node": Zap,
  "show-on-click": MousePointer2,
  "toggle-visible": ToggleLeft,
  "visibility-zone": Container,
  "minecraft-status-chip": Activity,
  "action-chip": Zap,
  "panel-visibility-select": ChevronDown,
  "play-show-bind": Play,
  "show-on-condition": Eye,
  "hide-on-condition": EyeOff,
  "launch-desktop-window-toggle": Monitor,
  "instance-create-button": FolderPlus,
  "profile-widget": User,
  "version-selector": Gamepad2,
  "stat-card": Hash,
  chip: Box,
  "progress-bar": Percent,
  container: Container,
  "surface-box": Square,
  divider: Minus,
  spacer: Minus,
  "script-button": Code2,
  toggle: ToggleLeft,
  "input-field": Type,
  slider: SlidersHorizontal,
  checkbox: CheckSquare,
  dropdown: ChevronDown,
  "api-call": Globe,
  timer: Timer,
  counter: Hash,
  "toast-trigger": Bell,
  "chrome-brand": PanelTop,
  "chrome-screen-title": Monitor,
  "chrome-status": Activity,
  "chrome-account": User,
  "chrome-button": MousePointer2,
  "chrome-icon-button": Square,
  "chrome-spacer": Minus,
  "chrome-divider": SeparatorVertical,
  "chrome-launch-progress": ScrollText,
};

export const logicBadgeIcon = Zap;
